---
version: 2

project_name: saml2aws-u2f

builds:
- id: saml2aws
  main: ./cmd/saml2aws/main.go
  binary: saml2aws
  flags:
    - -trimpath
    - -v
  ldflags:
    - -s -w -X main.Version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  goos:
    - linux
  goarch:
    - amd64
  overrides:
    - goos: linux
      goarch: amd64
      goamd64: v1
      tags:
        - hidraw
      env:
        - CGO_ENABLED=1
- id: saml2aws-static
  main: ./cmd/saml2aws/main.go
  binary: saml2aws
  flags:
    - -trimpath
    - -v
  ldflags:
    - -s -w -X main.Version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -extldflags "-static"
  goos:
    - linux
  goarch:
    - amd64
    - arm64
    - arm
  env:
    - CGO_ENABLED=0
archives:
  - id: saml2aws
    formats: [tar.gz]
    ids: [saml2aws]
    wrap_in_directory: false
    # remove README and LICENSE
    files:
      - LICENSE.md
      - README.md
  - id: saml2aws-static
    formats: [tar.gz]
    ids: [saml2aws-static]
    wrap_in_directory: false
    # remove README and LICENSE
    files:
      - LICENSE.md
      - README.md
    name_template: "{{ .ProjectName }}_static_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
dockers_v2:
  - ids: [saml2aws-static]
    images:
      - ghcr.io/{{ .Env.IMAGE_NAME }}
    tags:
      - "{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
